# 必须设置 site.url 才能生成正确的绝对链接

# theme: minima
url: "https://goalaid.github.io" 
baseurl: "" 

title: GoalAid
# description: "A simple and free (Android) app reminds the days left to your goal"
description:

# lang: "en"
author:
  email: 

# 在 2025 年，GitHub Pages 默认提供的 Jekyll 环境中，minima 主题默认使用的版本依然是 2.5.x 系列。
remote_theme: jekyll/minima@master

nav_pages:
  - README.md
  - blog.md
    
minima:
  # 可选值: classic, dark, auto, solarized, solarized-light, solarized-dark
  skin: solarized
  # 将此项设置为 true 即可隐藏页脚的 RSS 订阅图标/文字
  hide_site_feed_link: true

  date_format: "%Y-%m-%d"
  
  
# 添加下面这一行，禁止 SEO 插件自动生成可能有冲突的标签
seo:
  canonical: false

# 启用插件
plugins:
  - jekyll-remote-theme
  - jekyll-paginate-v2  # 注意：这需要开启 GitHub Actions 才能运行
  - jekyll-feed
#  - jekyll-default-layout

# future: true    # show posts with future dates

